baseURL: https://blog.nobody.ml/
languageCode: en-us
title: Nobody's Blog
theme: PaperMod
paginate: 5


enableRobotsTXT: true
buildDrafts: true

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production
    author: Nobody
    # images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    comments: true

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: /favicon.ico
        favicon16x16: /favicon-16x16.png
        favicon32x32: /favicon-32x32.png
        apple_touch_icon: /apple-touch-icon.png
        safari_pinned_tab: /favicon.ico

    label:
        text: Home
        icon: /apple-touch-icon.png
        # iconHeight: 35

    profileMode:
        enabled: true
        title: "Nobody's Blog"
        # subtitle: "Hi there \U0001F44B"
        imageUrl: /avatar.jpg
        imageWidth: 120
        imageHeight: 120
        imageTitle: my avatar
        buttons:
            - name: Posts
              url: posts
            - name: Search
              url: search

    socialIcons:
        - name: github
          url: https://github.com/YaphetS911
        - name: telegram
          url: https://t.me/YaphetS911
        - name: rss
          url: /index.xml
          
menu:
    main:
        - identifier: archives
          name: Archive
          url: /archives/
          weight: 10
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 30
        - identifier: search
          name: Search
          url: /search/
          weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
